### ISSUE TITLE
Please renew your SSL certificate

### ISSUE THREAD

**Issue by akc2267** [terra-project/jigu#9]
I can't send calls with parameters with jigu testnet because the SSL cert is expired.

`requests.exceptions.SSLError: HTTPSConnectionPool(host='soju-lcd.terra.dev', port=443): Max retries exceeded with url: /auth/accounts/terra1pqj9aec7wh2qlxwwhrxvts6vypeq3nd3xl5e6w (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')))
`
was trying

` wallet.balance('uluna')
`
@ouiliame @etienne-napoleone

**Comment by akc2267** [comment]
the example binder jupyter notebook is also broken:
![image](https://user-images.githubusercontent.com/10821110/101976680-56985f80-3c0d-11eb-9042-42383fce607b.png)

**Comment by etienne-napoleone** [comment]
Hello, `soju-0014` was retired a while ago.
Current testnet is `tequila-0004`.
I just updated our testnet repo to reflect this change: https://github.com/terra-project/testnet
